# Generated by Django 3.1.1 on 2020-11-06 11:53

import autoslug.fields
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='country_of_origin',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Страна происхождения'),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='firmness',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('soft', 'Soft'), ('semi-soft', 'Semi-Soft'), ('semi-hard', 'Semi-Hard'), ('hard', 'Hard')], default='unspecified', max_length=20, verbose_name='Твердость'),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название сыра'),
        ),
        migrations.AlterField(
            model_name='cheese',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Адрес сыра'),
        ),
    ]
